// Game Configuration File

// Icon ID constants - use these variables for better matching and to avoid typos
const ICON = {
  WOLF: "wolf",
  WIZARD: "wizard",
  WIZARDHAT: "wizardhat",
  BRAIN: "brain",
  HEART: "heart",
  HEARTBREAK: "heartbreak",
  TROPHY: "trophy",
  STAR: "star",
  FIRE: "fire",
  MONEY: "money",
  COIN: "coin",
  GOLDBAR: "goldbar",
  DIAMOND: "diamond",
  CROWN: "crown",
  GIFT: "gift",
  CLOCK: "clock",
  ALARMCLOCK: "alarmclock",
  STOPWATCH: "stopwatch",
  LOCK: "lock",
  BOOK: "book",
  LIGHTNING: "lightning",
  SPARKLES: "sparkles",
  WAND: "wand",
  GAUNTLET: "gauntlet",
  SKULL: "skull",
  DEMON: "demon",
  GOBLIN: "goblin",
  SOCK: "sock",
  MISMATCHSOCK: "mismatchsock",
  DIAMONDSOCK: "diamondsock",
  GOLDENSOCKS: "goldensocks",
  LAUNDRYPILE: "laundrypile",
  BASKET: "basket",
  HOUSE: "house",
  HOUSEFIRE: "housefire",
  TV: "tv",
  WASHINGMAC: "washingmac",
  CDPLAYER: "cdplayer",
  RADIO: "radio",
  VHS: "vhs",
  RECORD: "record",
  MUSICNOTE: "musicnote",
  BARBELL: "barbell",
  SHOES: "shoes",
  HAT: "hat",
  EGG: "egg",
  BUTTER: "butter",
  GLASS: "glass",
  HANDS: "hands",
  TEETH: "teeth",
  EYEBALL: "eyeball",
  BEETLE: "beetle",
  STAGBEETLE: "stagbeetle",
  MOUSE: "mouse",
  STROLLER: "stroller",
  WALL: "wall",
  BULLSEYE: "bullseye",
  REDX: "redx",
  MEDAL: "medal",
  SONIC: "sonic",
  SUNDIAL: "sundial",
  SNAPPY: "snappy",
  GOLDENSNAPPY: "goldensnappy",
  DIAMONDSNAPPY: "diamondsnappy",
  POKE: "pokeball",
  GOLDENORB: "goldenorb",
  DIAMONDTROPHY: "diamondtrophy",
  DIAMONDHEART: "diamondheart",
  ASTEROID: "asteroid",
};

// All available icons in the game
const GAME_ICONS = [
  {
    id: ICON.ASTEROID,
    file: "icon-asteroid.png",
    name: "Asteroid",
  },
  {
    id: ICON.DIAMONDHEART,
    file: "icon-diamondheart.png",
    name: "Diamond Heart",
  },
  {
    id: ICON.DIAMONDTROPHY,
    file: "icon-diamondtrophy.png",
    name: "Diamond Trophy",
  },
  { id: ICON.GOLDENORB, file: "icon-goldenorb.png", name: "Golden Orb" },
  {
    id: ICON.DIAMONDSNAPPY,
    file: "icon-diamondsnap.png",
    name: "Diamond Snap",
  },
  { id: ICON.GOLDENSNAPPY, file: "icon-goldsnap.png", name: "Golden Snap" },
  { id: ICON.WOLF, file: "icon-wolf.png", name: "Wolf" },
  { id: ICON.POKE, file: "icon-poke.png", name: "Pokeball" },
  { id: ICON.WIZARDHAT, file: "icon-wizard.png", name: "Wizard Hat" },
  { id: ICON.WIZARD, file: "icon-fullwizard.png", name: "Wizard" },
  { id: ICON.BRAIN, file: "icon-brain.png", name: "Brain" },
  { id: ICON.HEART, file: "icon-heart.png", name: "Heart" },
  { id: ICON.HEARTBREAK, file: "icon-heartbreak.png", name: "Heartbreak" },
  { id: ICON.TROPHY, file: "icon-trophy.png", name: "Trophy" },
  { id: ICON.STAR, file: "icon-star.png", name: "Star" },
  { id: ICON.FIRE, file: "icon-fire3.png", name: "Fire" },
  { id: ICON.MONEY, file: "icon-money.png", name: "Money" },
  { id: ICON.COIN, file: "icon-coin.png", name: "Coin" },
  { id: ICON.GOLDBAR, file: "icon-goldbar.png", name: "Gold Bar" },
  { id: ICON.DIAMOND, file: "icon-diamond.png", name: "Diamond" },
  { id: ICON.CROWN, file: "icon-crown.png", name: "Crown" },
  { id: ICON.GIFT, file: "icon-gift.png", name: "Gift" },
  { id: ICON.CLOCK, file: "icon-clock.png", name: "Clock" },
  { id: ICON.ALARMCLOCK, file: "icon-alarmclock.png", name: "Alarm Clock" },
  { id: ICON.STOPWATCH, file: "icon-stopwatch.png", name: "Stopwatch" },
  { id: ICON.LOCK, file: "icon-lock.png", name: "Lock" },
  { id: ICON.BOOK, file: "icon-book.png", name: "Book" },
  { id: ICON.LIGHTNING, file: "icon-lightning.png", name: "Lightning" },
  { id: ICON.SPARKLES, file: "icon-sparkles.png", name: "Sparkles" },
  { id: ICON.WAND, file: "icon-wand.png", name: "Wand" },
  { id: ICON.GAUNTLET, file: "icon-gauntlet.png", name: "Gauntlet" },
  { id: ICON.SKULL, file: "icon-skull.png", name: "Skull" },
  { id: ICON.DEMON, file: "icon-demon.png", name: "Demon" },
  { id: ICON.GOBLIN, file: "icon-goblin.png", name: "Goblin" },
  { id: ICON.SOCK, file: "icon-sock.png", name: "Sock" },
  { id: ICON.SNAPPY, file: "icon-snappy.png", name: "Snappy" },
  {
    id: ICON.MISMATCHSOCK,
    file: "icon-mismatchsock.png",
    name: "Mismatched Socks",
  },
  { id: ICON.DIAMONDSOCK, file: "icon-diamondsock.png", name: "Diamond Sock" },
  { id: ICON.GOLDENSOCKS, file: "icon-goldensocks.png", name: "Golden Socks" },
  { id: ICON.LAUNDRYPILE, file: "icon-laundrypile.png", name: "Laundry Pile" },
  { id: ICON.BASKET, file: "icon-basket.png", name: "Basket" },
  { id: ICON.HOUSE, file: "icon-house.png", name: "House" },
  { id: ICON.HOUSEFIRE, file: "icon-housefire.png", name: "House Fire" },
  { id: ICON.TV, file: "icon-tv.png", name: "TV" },
  { id: ICON.WASHINGMAC, file: "icon-washingmac.png", name: "Washing Machine" },
  { id: ICON.CDPLAYER, file: "icon-cdplayer.png", name: "CD Player" },
  { id: ICON.RADIO, file: "icon-radio.png", name: "Radio" },
  { id: ICON.VHS, file: "icon-vhs.png", name: "VHS" },
  { id: ICON.RECORD, file: "icon-record.png", name: "Record" },
  { id: ICON.MUSICNOTE, file: "icon-musicnote.png", name: "Music Note" },
  { id: ICON.BARBELL, file: "icon-barbell.png", name: "Barbell" },
  { id: ICON.SHOES, file: "icon-shoes.png", name: "Shoes" },
  { id: ICON.HAT, file: "icon-hat.png", name: "Hat" },
  { id: ICON.EGG, file: "icon-egg.png", name: "Egg" },
  { id: ICON.BUTTER, file: "icon-butter.png", name: "Butter" },
  { id: ICON.GLASS, file: "icon-glass.png", name: "Glass" },
  { id: ICON.HANDS, file: "icon-hands.png", name: "Praying Hands" },
  { id: ICON.TEETH, file: "icon-teeth.png", name: "Teeth" },
  { id: ICON.EYEBALL, file: "icon-eyeball.png", name: "Eyeball" },
  { id: ICON.BEETLE, file: "icon-beetle.png", name: "Beetle" },
  { id: ICON.STAGBEETLE, file: "icon-stagbeetle.png", name: "Stag Beetle" },
  { id: ICON.MOUSE, file: "icon-mouse.png", name: "Mouse" },
  { id: ICON.STROLLER, file: "icon-stroller.png", name: "Stroller" },
  { id: ICON.WALL, file: "icon-wall.png", name: "Wall" },
  { id: ICON.BULLSEYE, file: "icon-bullseye.png", name: "Bullseye" },
  { id: ICON.REDX, file: "icon-redx.png", name: "Red X" },
  { id: ICON.MEDAL, file: "icon-1stmedal.png", name: "1st Medal" },
  { id: ICON.SONIC, file: "icon-sonic.png", name: "Sonic" },
  { id: ICON.SUNDIAL, file: "icon-sundial.png", name: "Sun Dial" },
];

// Post messages with icon reactions
// Each post has:
// - text: The message displayed to the player
// - perfectIcons: Array of icon IDs that give +5 points (perfect answers)
// - correctIcons: Array of icon IDs that give +2 points (good answers)
// - neutralIcons: Array of icon IDs that give 0 points (okay answers)
// - wrongIcons: Array of icon IDs that give -3 points (bad answers)
// - horribleIcons: Array of icon IDs that give -6 points (terrible answers)

const GAME_MESSAGES = [
  {
    text: "Laundry pile achieved sentience. Negotiating terms of surrender.",
    perfectIcons: [ICON.LAUNDRYPILE],
    correctIcons: [ICON.DEMON],
    neutralIcons: [ICON.BRAIN, ICON.HANDS],
    wrongIcons: [ICON.HEART],
    horribleIcons: [ICON.POKE],
  },
  {
    text: "Alarm went off. Body said 'counterpoint: no.'",
    perfectIcons: [ICON.ALARMCLOCK],
    correctIcons: [ICON.SKULL],
    neutralIcons: [ICON.HEARTBREAK, ICON.BRAIN],
    wrongIcons: [ICON.TROPHY],
    horribleIcons: [ICON.STAR],
  },
  {
    text: "Kitchen experiment reached its final form. Smoke detector applauded.",
    perfectIcons: [ICON.HOUSEFIRE],
    correctIcons: [ICON.FIRE],
    neutralIcons: [ICON.SPARKLES, ICON.GLASS],
    wrongIcons: [ICON.HEART],
    horribleIcons: [ICON.STROLLER],
  },
  {
    text: "Found the missing piece. It was in my hand the whole time.",
    perfectIcons: [ICON.HANDS],
    correctIcons: [ICON.BRAIN],
    neutralIcons: [ICON.EYEBALL, ICON.LIGHTNING],
    wrongIcons: [ICON.DEMON],
    horribleIcons: [ICON.MOUSE],
  },
  {
    text: "Parallel parked on the first try. Witnesses requested autographs.",
    perfectIcons: [ICON.TROPHY],
    correctIcons: [ICON.MEDAL],
    neutralIcons: [ICON.STAR, ICON.CROWN],
    wrongIcons: [ICON.LAUNDRYPILE],
    horribleIcons: [ICON.MISMATCHSOCK],
  },
  {
    text: "Became a wizard at forgetting where I put my keys.",
    perfectIcons: [ICON.WIZARD],
    correctIcons: [ICON.LOCK],
    neutralIcons: [ICON.BRAIN, ICON.WAND],
    wrongIcons: [ICON.TROPHY],
    horribleIcons: [ICON.HEART],
  },
  {
    text: "Tried to adult today. My credit card declined.",
    perfectIcons: [ICON.HEARTBREAK],
    correctIcons: [ICON.MONEY],
    neutralIcons: [ICON.REDX, ICON.SKULL],
    wrongIcons: [ICON.STAR],
    horribleIcons: [ICON.SPARKLES],
  },
  {
    text: "Socks have entered the chat. I'm losing the war.",
    perfectIcons: [ICON.MISMATCHSOCK],
    correctIcons: [ICON.LAUNDRYPILE],
    neutralIcons: [ICON.SOCK, ICON.DEMON],
    wrongIcons: [ICON.TROPHY],
    horribleIcons: [ICON.HEART],
  },
  {
    text: "My houseplant survived another day. We both deserve medals.",
    perfectIcons: [ICON.MEDAL],
    correctIcons: [ICON.HEART],
    neutralIcons: [ICON.TROPHY, ICON.SPARKLES],
    wrongIcons: [ICON.FIRE],
    horribleIcons: [ICON.HOUSEFIRE],
  },
  {
    text: "Hit snooze so many times, I'm now five hours late.",
    perfectIcons: [ICON.CLOCK],
    correctIcons: [ICON.ALARMCLOCK],
    neutralIcons: [ICON.STOPWATCH, ICON.HEARTBREAK],
    wrongIcons: [ICON.STAR],
    horribleIcons: [ICON.TROPHY],
  },
  {
    text: "Told a joke and nobody laughed. Truly the funniest moment.",
    perfectIcons: [ICON.REDX],
    correctIcons: [ICON.HEARTBREAK],
    neutralIcons: [ICON.SKULL, ICON.DEMON],
    wrongIcons: [ICON.STAR],
    horribleIcons: [ICON.CROWN],
  },
  {
    text: "Successfully opened a jar. My career peak has been reached.",
    perfectIcons: [ICON.TROPHY],
    correctIcons: [ICON.HANDS],
    neutralIcons: [ICON.GLASS, ICON.MEDAL],
    wrongIcons: [ICON.LAUNDRYPILE],
    horribleIcons: [ICON.STROLLER],
  },
  {
    text: "Finally understood that confusing plot twist. Three years later.",
    perfectIcons: [ICON.BRAIN],
    correctIcons: [ICON.LIGHTNING],
    neutralIcons: [ICON.CLOCK, ICON.SPARKLES],
    wrongIcons: [ICON.HEARTBREAK],
    horribleIcons: [ICON.MOUSE],
  },
  {
    text: "My coffee is still hot. Today will be legendary.",
    perfectIcons: [ICON.FIRE],
    correctIcons: [ICON.HEART],
    neutralIcons: [ICON.SPARKLES, ICON.STAR],
    wrongIcons: [ICON.LAUNDRYPILE],
    horribleIcons: [ICON.BEETLE],
  },
  {
    text: "Wore matching socks. I am unstoppable.",
    perfectIcons: [ICON.GOLDENSOCKS],
    correctIcons: [ICON.TROPHY],
    neutralIcons: [ICON.SOCK, ICON.STAR],
    wrongIcons: [ICON.FIRE],
    horribleIcons: [ICON.HOUSEFIRE],
  },
  {
    text: "Made it through the day without checking my emails. Revolutionary.",
    perfectIcons: [ICON.SPARKLES],
    correctIcons: [ICON.STAR],
    neutralIcons: [ICON.HEART, ICON.MEDAL],
    wrongIcons: [ICON.ALARMCLOCK],
    horribleIcons: [ICON.HEARTBREAK],
  },
  {
    text: "Remembered to water my plant. Peak life moment.",
    perfectIcons: [ICON.HEART],
    correctIcons: [ICON.SPARKLES],
    neutralIcons: [ICON.MEDAL, ICON.STAR],
    wrongIcons: [ICON.FIRE],
    horribleIcons: [ICON.HOUSEFIRE],
  },
  {
    text: "Finally organized my desk. Please admire my achievement.",
    perfectIcons: [ICON.TROPHY],
    correctIcons: [ICON.MEDAL],
    neutralIcons: [ICON.STAR, ICON.SPARKLES],
    wrongIcons: [ICON.LAUNDRYPILE],
    horribleIcons: [ICON.MISMATCHSOCK],
  },
  {
    text: "Returned the shopping cart. Society owes me a fortune.",
    perfectIcons: [ICON.HEART],
    correctIcons: [ICON.MEDAL],
    neutralIcons: [ICON.STAR, ICON.SPARKLES],
    wrongIcons: [ICON.MONEY],
    horribleIcons: [ICON.HOUSEFIRE],
  },
  {
    text: "My internet didn't disconnect during the meeting. Blessed.",
    perfectIcons: [ICON.SPARKLES],
    correctIcons: [ICON.STAR],
    neutralIcons: [ICON.LIGHTNING, ICON.HEART],
    wrongIcons: [ICON.REDX],
    horribleIcons: [ICON.HOUSEFIRE],
  },
  {
    text: "Baked something that didn't burn. I'm basically a chef now.",
    perfectIcons: [ICON.TROPHY],
    correctIcons: [ICON.STAR],
    neutralIcons: [ICON.MEDAL, ICON.FIRE],
    wrongIcons: [ICON.HOUSEFIRE],
    horribleIcons: [ICON.LAUNDRYPILE],
  },
  {
    text: "Matched all my socks into pairs. Witchcraft confirmed.",
    perfectIcons: [ICON.WIZARD],
    correctIcons: [ICON.GOLDENSOCKS],
    neutralIcons: [ICON.WAND, ICON.SPARKLES],
    wrongIcons: [ICON.HOUSEFIRE],
    horribleIcons: [ICON.FIRE],
  },
  {
    text: "Finished reading a book before buying three more. Addiction confirmed.",
    perfectIcons: [ICON.BOOK],
    correctIcons: [ICON.SPARKLES],
    neutralIcons: [ICON.HEART, ICON.STAR],
    wrongIcons: [ICON.LAUNDRYPILE],
    horribleIcons: [ICON.FIRE],
  },
  {
    text: "Ran out of coffee mid-Monday. This is how it ends.",
    perfectIcons: [ICON.HEARTBREAK],
    correctIcons: [ICON.DEMON],
    neutralIcons: [ICON.SKULL, ICON.REDX],
    wrongIcons: [ICON.TROPHY],
    horribleIcons: [ICON.STAR],
  },
  {
    text: "Answered an email immediately. I regret all my choices.",
    perfectIcons: [ICON.HEARTBREAK],
    correctIcons: [ICON.BRAIN],
    neutralIcons: [ICON.CLOCK, ICON.LIGHTNING],
    wrongIcons: [ICON.TROPHY],
    horribleIcons: [ICON.STAR],
  },
  {
    text: "Made a to-do list and actually finished it. Who am I?",
    perfectIcons: [ICON.TROPHY],
    correctIcons: [ICON.MEDAL],
    neutralIcons: [ICON.STAR, ICON.SPARKLES],
    wrongIcons: [ICON.LAUNDRYPILE],
    horribleIcons: [ICON.HEARTBREAK],
  },
  {
    text: "Wore my lucky socks. Everything is now possible.",
    perfectIcons: [ICON.DIAMONDSOCK],
    correctIcons: [ICON.TROPHY],
    neutralIcons: [ICON.STAR, ICON.SPARKLES],
    wrongIcons: [ICON.FIRE],
    horribleIcons: [ICON.LAUNDRYPILE],
  },
  {
    text: "The universe delivered exactly what I ordered. Miracles exist.",
    perfectIcons: [ICON.SPARKLES],
    correctIcons: [ICON.CROWN],
    neutralIcons: [ICON.STAR, ICON.DIAMOND],
    wrongIcons: [ICON.REDX],
    horribleIcons: [ICON.HEARTBREAK],
  },
  {
    text: "Remembered my password on the first try. I'm a genius.",
    perfectIcons: [ICON.BRAIN],
    correctIcons: [ICON.STAR],
    neutralIcons: [ICON.LIGHTNING, ICON.SPARKLES],
    wrongIcons: [ICON.LOCK],
    horribleIcons: [ICON.HEARTBREAK],
  },
  {
    text: "Folded a fitted sheet correctly. I've peaked.",
    perfectIcons: [ICON.TROPHY],
    correctIcons: [ICON.MEDAL],
    neutralIcons: [ICON.BASKET, ICON.SPARKLES],
    wrongIcons: [ICON.HEARTBREAK],
    horribleIcons: [ICON.LAUNDRYPILE],
  },
  {
    text: "Channeled my inner wolf and howled at the moon. Neighbors loved it.",
    perfectIcons: [ICON.WOLF],
    correctIcons: [ICON.DEMON],
    neutralIcons: [ICON.GOBLIN, ICON.LIGHTNING],
    wrongIcons: [ICON.HEART],
    horribleIcons: [ICON.TROPHY],
  },
  {
    text: "Solved the mystery. The butler did nothing interesting.",
    perfectIcons: [ICON.BOOK],
    correctIcons: [ICON.BRAIN],
    neutralIcons: [ICON.LIGHTNING, ICON.SPARKLES],
    wrongIcons: [ICON.FIRE],
    horribleIcons: [ICON.STROLLER],
  },
  {
    text: "My bank account whispered sweet nothings. They were lies.",
    perfectIcons: [ICON.MONEY],
    correctIcons: [ICON.HEARTBREAK],
    neutralIcons: [ICON.COIN, ICON.REDX],
    wrongIcons: [ICON.STAR],
    horribleIcons: [ICON.TROPHY],
  },
  {
    text: "Found a diamond. It was my determination after all.",
    perfectIcons: [ICON.DIAMOND],
    correctIcons: [ICON.STAR],
    neutralIcons: [ICON.SPARKLES, ICON.CROWN],
    wrongIcons: [ICON.HEARTBREAK],
    horribleIcons: [ICON.HOUSEFIRE],
  },
  {
    text: "Crowned myself ruler of my domain. Scepter not included.",
    perfectIcons: [ICON.CROWN],
    correctIcons: [ICON.GAUNTLET],
    neutralIcons: [ICON.TROPHY, ICON.MEDAL],
    wrongIcons: [ICON.HEARTBREAK],
    horribleIcons: [ICON.LAUNDRYPILE],
  },
  {
    text: "Opened my gift. It was what I asked for. Witchcraft.",
    perfectIcons: [ICON.GIFT],
    correctIcons: [ICON.SPARKLES],
    neutralIcons: [ICON.HEART, ICON.STAR],
    wrongIcons: [ICON.REDX],
    horribleIcons: [ICON.HOUSEFIRE],
  },
  {
    text: "Watched a lightning bolt strike and felt seen.",
    perfectIcons: [ICON.LIGHTNING],
    correctIcons: [ICON.FIRE],
    neutralIcons: [ICON.SPARKLES, ICON.DEMON],
    wrongIcons: [ICON.HEART],
    horribleIcons: [ICON.STROLLER],
  },
  {
    text: "My wand broke. I'm just a regular person now.",
    perfectIcons: [ICON.WAND],
    correctIcons: [ICON.HEARTBREAK],
    neutralIcons: [ICON.WIZARD, ICON.BRAIN],
    wrongIcons: [ICON.TROPHY],
    horribleIcons: [ICON.STAR],
  },
  {
    text: "Found my keys on my keychain. Peak detective work.",
    perfectIcons: [ICON.LOCK],
    correctIcons: [ICON.BRAIN],
    neutralIcons: [ICON.EYEBALL, ICON.LIGHTNING],
    wrongIcons: [ICON.LAUNDRYPILE],
    horribleIcons: [ICON.STROLLER],
  },
  {
    text: "My teeth fell out. Just kidding, I'm smiling.",
    perfectIcons: [ICON.TEETH],
    correctIcons: [ICON.HEART],
    neutralIcons: [ICON.SPARKLES, ICON.STAR],
    wrongIcons: [ICON.FIRE],
    horribleIcons: [ICON.SKULL],
  },
  {
    text: "Became one with the eyeball. Now I see all.",
    perfectIcons: [ICON.EYEBALL],
    correctIcons: [ICON.BRAIN],
    neutralIcons: [ICON.LIGHTNING, ICON.WIZARD],
    wrongIcons: [ICON.HOUSEFIRE],
    horribleIcons: [ICON.LAUNDRYPILE],
  },
  {
    text: "A beetle invaded my space. We negotiated peace.",
    perfectIcons: [ICON.BEETLE],
    correctIcons: [ICON.DEMON],
    neutralIcons: [ICON.STAGBEETLE, ICON.GOBLIN],
    wrongIcons: [ICON.HEART],
    horribleIcons: [ICON.TROPHY],
  },
  {
    text: "The mouse in my house is roommate-adjacent now.",
    perfectIcons: [ICON.MOUSE],
    correctIcons: [ICON.STROLLER],
    neutralIcons: [ICON.BEETLE, ICON.HOUSE],
    wrongIcons: [ICON.TROPHY],
    horribleIcons: [ICON.STAR],
  },
  {
    text: "My house is standing. That's an achievement.",
    perfectIcons: [ICON.HOUSE],
    correctIcons: [ICON.HEART],
    neutralIcons: [ICON.WALL, ICON.SPARKLES],
    wrongIcons: [ICON.FIRE],
    horribleIcons: [ICON.HOUSEFIRE],
  },
  {
    text: "Hit the bullseye on my first attempt. Beginner's luck.",
    perfectIcons: [ICON.BULLSEYE],
    correctIcons: [ICON.TROPHY],
    neutralIcons: [ICON.STAR, ICON.MEDAL],
    wrongIcons: [ICON.LAUNDRYPILE],
    horribleIcons: [ICON.STROLLER],
  },
  {
    text: "Lifted the barbell. My muscles now have muscles.",
    perfectIcons: [ICON.BARBELL],
    correctIcons: [ICON.TROPHY],
    neutralIcons: [ICON.GAUNTLET, ICON.MEDAL],
    wrongIcons: [ICON.HEART],
    horribleIcons: [ICON.LAUNDRYPILE],
  },
  {
    text: "Put on my shoes. I'm basically ready for anything.",
    perfectIcons: [ICON.SHOES],
    correctIcons: [ICON.STAR],
    neutralIcons: [ICON.GOLDENSOCKS, ICON.SPARKLES],
    wrongIcons: [ICON.HEARTBREAK],
    horribleIcons: [ICON.HOUSEFIRE],
  },
  {
    text: "Found the hat. Now I'm a wizard. Probably.",
    perfectIcons: [ICON.HAT],
    correctIcons: [ICON.WIZARD],
    neutralIcons: [ICON.WIZARDHAT, ICON.WAND],
    wrongIcons: [ICON.HEARTBREAK],
    horribleIcons: [ICON.LAUNDRYPILE],
  },
  {
    text: "Cracked an egg without getting shell bits. Evolution.",
    perfectIcons: [ICON.EGG],
    correctIcons: [ICON.HANDS],
    neutralIcons: [ICON.GLASS, ICON.SPARKLES],
    wrongIcons: [ICON.FIRE],
    horribleIcons: [ICON.HOUSEFIRE],
  },
  {
    text: "Spread butter like an artist. The toast is confused.",
    perfectIcons: [ICON.BUTTER],
    correctIcons: [ICON.HANDS],
    neutralIcons: [ICON.SPARKLES, ICON.STAR],
    wrongIcons: [ICON.HEARTBREAK],
    horribleIcons: [ICON.DEMON],
  },
  {
    text: "My glass is half full. Or I'm just thirsty.",
    perfectIcons: [ICON.GLASS],
    correctIcons: [ICON.HEART],
    neutralIcons: [ICON.SPARKLES, ICON.STAR],
    wrongIcons: [ICON.FIRE],
    horribleIcons: [ICON.HOUSEFIRE],
  },
  {
    text: "The record spun perfectly. My music taste remains unquestioned.",
    perfectIcons: [ICON.RECORD],
    correctIcons: [ICON.STAR],
    neutralIcons: [ICON.MUSICNOTE, ICON.SPARKLES],
    wrongIcons: [ICON.HEARTBREAK],
    horribleIcons: [ICON.LAUNDRYPILE],
  },
  {
    text: "Played a music note and nobody said 'wrong.' Progress.",
    perfectIcons: [ICON.MUSICNOTE],
    correctIcons: [ICON.HEART],
    neutralIcons: [ICON.RECORD, ICON.SPARKLES],
    wrongIcons: [ICON.REDX],
    horribleIcons: [ICON.HOUSEFIRE],
  },
  {
    text: "The stopwatch says I'm winning at time management.",
    perfectIcons: [ICON.STOPWATCH],
    correctIcons: [ICON.TROPHY],
    neutralIcons: [ICON.CLOCK, ICON.MEDAL],
    wrongIcons: [ICON.HEARTBREAK],
    horribleIcons: [ICON.LAUNDRYPILE],
  },
  {
    text: "Connected my hands and made something happen.",
    perfectIcons: [ICON.HANDS],
    correctIcons: [ICON.SPARKLES],
    neutralIcons: [ICON.BRAIN, ICON.LIGHTNING],
    wrongIcons: [ICON.FIRE],
    horribleIcons: [ICON.STROLLER],
  },
  {
    text: "The sonic boom of my existence just hit.",
    perfectIcons: [ICON.SONIC],
    correctIcons: [ICON.LIGHTNING],
    neutralIcons: [ICON.SPARKLES, ICON.STAR],
    wrongIcons: [ICON.HEARTBREAK],
    horribleIcons: [ICON.LAUNDRYPILE],
  },
  {
    text: "My golden snappy snapped perfectly. Perfection unlocked.",
    perfectIcons: [ICON.GOLDENSNAPPY],
    correctIcons: [ICON.TROPHY],
    neutralIcons: [ICON.SNAPPY, ICON.STAR],
    wrongIcons: [ICON.HEARTBREAK],
    horribleIcons: [ICON.HOUSEFIRE],
  },
  {
    text: "The diamond snappy caught the light. I'm sparkling.",
    perfectIcons: [ICON.DIAMONDSNAPPY],
    correctIcons: [ICON.SPARKLES],
    neutralIcons: [ICON.DIAMOND, ICON.STAR],
    wrongIcons: [ICON.LAUNDRYPILE],
    horribleIcons: [ICON.HEARTBREAK],
  },
  {
    text: "Caught a Pokémon with one hand behind my back.",
    perfectIcons: [ICON.POKE],
    correctIcons: [ICON.TROPHY],
    neutralIcons: [ICON.STAR, ICON.MEDAL],
    wrongIcons: [ICON.HEARTBREAK],
    horribleIcons: [ICON.HOUSEFIRE],
  },
  {
    text: "Held a golden orb. Instantly became a fortune teller.",
    perfectIcons: [ICON.GOLDENORB],
    correctIcons: [ICON.WIZARD],
    neutralIcons: [ICON.SPARKLES, ICON.WAND],
    wrongIcons: [ICON.HEARTBREAK],
    horribleIcons: [ICON.LAUNDRYPILE],
  },
  {
    text: "Won the diamond trophy. My shelf has achieved sentience.",
    perfectIcons: [ICON.DIAMONDTROPHY],
    correctIcons: [ICON.TROPHY],
    neutralIcons: [ICON.DIAMOND, ICON.MEDAL],
    wrongIcons: [ICON.LAUNDRYPILE],
    horribleIcons: [ICON.HOUSEFIRE],
  },
  {
    text: "My heart turned to diamonds. Literally unbreakable now.",
    perfectIcons: [ICON.DIAMONDHEART],
    correctIcons: [ICON.SPARKLES],
    neutralIcons: [ICON.DIAMOND, ICON.HEART],
    wrongIcons: [ICON.FIRE],
    horribleIcons: [ICON.HOUSEFIRE],
  },
  {
    text: "An asteroid just missed my house. Close call.",
    perfectIcons: [ICON.ASTEROID],
    correctIcons: [ICON.HOUSE],
    neutralIcons: [ICON.HOUSEFIRE, ICON.LIGHTNING],
    wrongIcons: [ICON.HEART],
    horribleIcons: [ICON.TROPHY],
  },
  {
    text: "Rewound my VHS tape. Nostalgia activated.",
    perfectIcons: [ICON.VHS],
    correctIcons: [ICON.RECORD],
    neutralIcons: [ICON.CDPLAYER, ICON.TV],
    wrongIcons: [ICON.LAUNDRYPILE],
    horribleIcons: [ICON.STROLLER],
  },
  {
    text: "Tuned the radio to my favorite station. Fate exists.",
    perfectIcons: [ICON.RADIO],
    correctIcons: [ICON.HEART],
    neutralIcons: [ICON.MUSICNOTE, ICON.SPARKLES],
    wrongIcons: [ICON.FIRE],
    horribleIcons: [ICON.DEMON],
  },
  {
    text: "The CD player spun without skipping. Miracles are real.",
    perfectIcons: [ICON.CDPLAYER],
    correctIcons: [ICON.STAR],
    neutralIcons: [ICON.RECORD, ICON.SPARKLES],
    wrongIcons: [ICON.HEARTBREAK],
    horribleIcons: [ICON.HOUSEFIRE],
  },
  {
    text: "My TV actually turned on when I pressed the button.",
    perfectIcons: [ICON.TV],
    correctIcons: [ICON.SPARKLES],
    neutralIcons: [ICON.STAR, ICON.HEART],
    wrongIcons: [ICON.HEARTBREAK],
    horribleIcons: [ICON.LAUNDRYPILE],
  },
  {
    text: "The washing machine didn't eat my socks today.",
    perfectIcons: [ICON.WASHINGMAC],
    correctIcons: [ICON.HEART],
    neutralIcons: [ICON.BASKET, ICON.SPARKLES],
    wrongIcons: [ICON.MISMATCHSOCK],
    horribleIcons: [ICON.HOUSEFIRE],
  },
  {
    text: "Discovered a new wall in my house. Redecorating planned.",
    perfectIcons: [ICON.WALL],
    correctIcons: [ICON.HOUSE],
    neutralIcons: [ICON.SPARKLES, ICON.STAR],
    wrongIcons: [ICON.HEARTBREAK],
    horribleIcons: [ICON.HOUSEFIRE],
  },
  {
    text: "Summoned a goblin for technical support. Worth it.",
    perfectIcons: [ICON.GOBLIN],
    correctIcons: [ICON.BRAIN],
    neutralIcons: [ICON.DEMON, ICON.WIZARD],
    wrongIcons: [ICON.HEART],
    horribleIcons: [ICON.TROPHY],
  },
  {
    text: "Wore my wizard hat to the grocery store. Regrets: none.",
    perfectIcons: [ICON.WIZARDHAT],
    correctIcons: [ICON.HAT],
    neutralIcons: [ICON.WIZARD, ICON.WAND],
    wrongIcons: [ICON.HEARTBREAK],
    horribleIcons: [ICON.LAUNDRYPILE],
  },
  {
    text: "Gazed into the stage beetle's eyes. Ancient wisdom transferred.",
    perfectIcons: [ICON.STAGBEETLE],
    correctIcons: [ICON.BRAIN],
    neutralIcons: [ICON.BEETLE, ICON.WIZARD],
    wrongIcons: [ICON.FIRE],
    horribleIcons: [ICON.HOUSEFIRE],
  },
  {
    text: "Pushed my cart to the store. Maximum effort achieved.",
    perfectIcons: [ICON.BASKET],
    correctIcons: [ICON.HEART],
    neutralIcons: [ICON.HANDS, ICON.SPARKLES],
    wrongIcons: [ICON.LAUNDRYPILE],
    horribleIcons: [ICON.HEARTBREAK],
  },
  {
    text: "Obtained the gold bar. Retirement is now feasible.",
    perfectIcons: [ICON.GOLDBAR],
    correctIcons: [ICON.MONEY],
    neutralIcons: [ICON.DIAMOND, ICON.COIN],
    wrongIcons: [ICON.HEARTBREAK],
    horribleIcons: [ICON.HOUSEFIRE],
  },
  {
    text: "Flipped a coin and landed on heads. Destiny confirmed.",
    perfectIcons: [ICON.COIN],
    correctIcons: [ICON.STAR],
    neutralIcons: [ICON.MONEY, ICON.SPARKLES],
    wrongIcons: [ICON.REDX],
    horribleIcons: [ICON.LAUNDRYPILE],
  },
  {
    text: "Contemplated my skull in the mirror. Hamlet energy.",
    perfectIcons: [ICON.SKULL],
    correctIcons: [ICON.BRAIN],
    neutralIcons: [ICON.DEMON, ICON.BOOK],
    wrongIcons: [ICON.HEART],
    horribleIcons: [ICON.TROPHY],
  },
  {
    text: "Sundial told me the time. Magic confirmed.",
    perfectIcons: [ICON.SUNDIAL],
    correctIcons: [ICON.CLOCK],
    neutralIcons: [ICON.SPARKLES, ICON.WIZARD],
    wrongIcons: [ICON.HEARTBREAK],
    horribleIcons: [ICON.HOUSEFIRE],
  },
  {
    text: "Snapped my fingers and something actually happened.",
    perfectIcons: [ICON.SNAPPY],
    correctIcons: [ICON.SPARKLES],
    neutralIcons: [ICON.HANDS, ICON.LIGHTNING],
    wrongIcons: [ICON.LAUNDRYPILE],
    horribleIcons: [ICON.HEARTBREAK],
  },
  {
    text: "Everything went perfectly. Like, suspiciously perfectly.",
    perfectIcons: [ICON.SPARKLES],
    correctIcons: [ICON.STAR],
    neutralIcons: [ICON.HEART, ICON.MEDAL],
    wrongIcons: [ICON.BEETLE],
    horribleIcons: [ICON.REDX],
  },
  {
    text: "Won the lottery. Then woke up.",
    perfectIcons: [ICON.STAR],
    correctIcons: [ICON.TROPHY],
    neutralIcons: [ICON.MEDAL, ICON.DIAMOND],
    wrongIcons: [ICON.MOUSE],
    horribleIcons: [ICON.HOUSEFIRE],
  },
  {
    text: "My gauntlet is ready for anything now.",
    perfectIcons: [ICON.GAUNTLET],
    correctIcons: [ICON.TROPHY],
    neutralIcons: [ICON.BARBELL, ICON.MEDAL],
    wrongIcons: [ICON.STAGBEETLE],
    horribleIcons: [ICON.HEARTBREAK],
  },
  {
    text: "Channeled pure demon energy. People noticed.",
    perfectIcons: [ICON.DEMON],
    correctIcons: [ICON.LIGHTNING],
    neutralIcons: [ICON.FIRE, ICON.SPARKLES],
    wrongIcons: [ICON.STROLLER],
    horribleIcons: [ICON.MUSICNOTE],
  },
  {
    text: "Achieved perfect sock synchronization across dimensions.",
    perfectIcons: [ICON.GOLDENSOCKS],
    correctIcons: [ICON.SPARKLES],
    neutralIcons: [ICON.DIAMONDSOCK, ICON.STAR],
    wrongIcons: [ICON.RADIO],
    horribleIcons: [ICON.EGG],
  },
  {
    text: "My heart broke but then turned to gold.",
    perfectIcons: [ICON.HEARTBREAK],
    correctIcons: [ICON.GOLDBAR],
    neutralIcons: [ICON.DIAMOND, ICON.SPARKLES],
    wrongIcons: [ICON.VHS],
    horribleIcons: [ICON.WASHINGMAC],
  },
  {
    text: "Lifted the gauntlet and became legend.",
    perfectIcons: [ICON.GAUNTLET],
    correctIcons: [ICON.TROPHY],
    neutralIcons: [ICON.BARBELL, ICON.MEDAL],
    wrongIcons: [ICON.CDPLAYER],
    horribleIcons: [ICON.BUTTER],
  },
  {
    text: "The medal on my chest gleams with purpose.",
    perfectIcons: [ICON.MEDAL],
    correctIcons: [ICON.TROPHY],
    neutralIcons: [ICON.STAR, ICON.CROWN],
    wrongIcons: [ICON.GLASS],
    horribleIcons: [ICON.WALL],
  },
  {
    text: "Sonic speed achieved. The world can't keep up.",
    perfectIcons: [ICON.SONIC],
    correctIcons: [ICON.LIGHTNING],
    neutralIcons: [ICON.STAR, ICON.SPARKLES],
    wrongIcons: [ICON.TV],
    horribleIcons: [ICON.HAT],
  },
  {
    text: "My golden orb predicted total success.",
    perfectIcons: [ICON.GOLDENORB],
    correctIcons: [ICON.STAR],
    neutralIcons: [ICON.SPARKLES, ICON.WIZARD],
    wrongIcons: [ICON.BASKET],
    horribleIcons: [ICON.COIN],
  },
  {
    text: "Won the diamond trophy in a landslide.",
    perfectIcons: [ICON.DIAMONDTROPHY],
    correctIcons: [ICON.TROPHY],
    neutralIcons: [ICON.DIAMOND, ICON.MEDAL],
    wrongIcons: [ICON.RECORD],
    horribleIcons: [ICON.SHOES],
  },
  {
    text: "My diamond heart can't be broken anymore.",
    perfectIcons: [ICON.DIAMONDHEART],
    correctIcons: [ICON.SPARKLES],
    neutralIcons: [ICON.DIAMOND, ICON.HEART],
    wrongIcons: [ICON.HANDS],
    horribleIcons: [ICON.SUNDIAL],
  },
  {
    text: "Gazed into infinity through my diamond snappy.",
    perfectIcons: [ICON.DIAMONDSNAPPY],
    correctIcons: [ICON.SPARKLES],
    neutralIcons: [ICON.DIAMOND, ICON.STAR],
    wrongIcons: [ICON.TEETH],
    horribleIcons: [ICON.EYEBALL],
  },
  {
    text: "Discovered the perfect snappy moment.",
    perfectIcons: [ICON.SNAPPY],
    correctIcons: [ICON.SPARKLES],
    neutralIcons: [ICON.HANDS, ICON.STAR],
    wrongIcons: [ICON.LOCK],
    horribleIcons: [ICON.BOOK],
  },
  {
    text: "The pokéball glowed with legendary energy.",
    perfectIcons: [ICON.POKE],
    correctIcons: [ICON.SPARKLES],
    neutralIcons: [ICON.STAR, ICON.LIGHTNING],
    wrongIcons: [ICON.WAND],
    horribleIcons: [ICON.CLOCK],
  },
  {
    text: "Activated my golden snappy at the perfect moment.",
    perfectIcons: [ICON.GOLDENSNAPPY],
    correctIcons: [ICON.TROPHY],
    neutralIcons: [ICON.SNAPPY, ICON.MEDAL],
    wrongIcons: [ICON.STOPWATCH],
    horribleIcons: [ICON.ALARMCLOCK],
  },
  {
    text: "My gift contained my wildest dreams.",
    perfectIcons: [ICON.GIFT],
    correctIcons: [ICON.HEART],
    neutralIcons: [ICON.SPARKLES, ICON.STAR],
    wrongIcons: [ICON.GAUNTLET],
    horribleIcons: [ICON.LAUNDRYPILE],
  },
  {
    text: "The wolf inside me finally emerged.",
    perfectIcons: [ICON.WOLF],
    correctIcons: [ICON.LIGHTNING],
    neutralIcons: [ICON.DEMON, ICON.FIRE],
    wrongIcons: [ICON.MONEY],
    horribleIcons: [ICON.MISMATCHSOCK],
  },
  {
    text: "Seized the crown and my destiny with it.",
    perfectIcons: [ICON.CROWN],
    correctIcons: [ICON.TROPHY],
    neutralIcons: [ICON.MEDAL, ICON.STAR],
    wrongIcons: [ICON.GOLDBAR],
    horribleIcons: [ICON.HEARTBREAK],
  },
  {
    text: "My windfall in shoes led to unexpected wisdom.",
    perfectIcons: [ICON.SHOES],
    correctIcons: [ICON.STAR],
    neutralIcons: [ICON.HAT, ICON.SPARKLES],
    wrongIcons: [ICON.DIAMOND],
    horribleIcons: [ICON.HEART],
  },
  {
    text: "Never wanted this - but here we are.",
    perfectIcons: [ICON.SHOES],
    correctIcons: [ICON.STAR],
    neutralIcons: [ICON.HAT, ICON.SPARKLES],
    wrongIcons: [ICON.DIAMOND],
    horribleIcons: [ICON.HEART],
  },
];

// Game scoring settings
const GAME_SCORING = {
  perfectPoints: 5, // Points for perfect icon
  correctPoints: 2, // Points for correct icon
  neutralPoints: 0, // Points for neutral icon
  wrongPoints: -3, // Points for wrong icon
  horriblePoints: -6, // Points for horrible icon
  timeoutPenalty: -2, // Points lost when time runs out
  fastBonus: 2, // Bonus for <1s reaction
  quickBonus: 1, // Bonus for <2s reaction
  targetScore: 100, // Score needed to win
  streak5Multiplier: 2, // Multiplier at 5 streak
  streak10Multiplier: 3, // Multiplier at 10 streak
  postTimeLimit: 10000, // Time limit per post in milliseconds (10 seconds)
};
