// Game Configuration File

// Icon ID constants - use these variables for better matching and to avoid typos
const ICON = {
  WOLF: "wolf",
  WIZARD: "wizard",
  WIZARDHAT: "wizardhat",
  BRAIN: "brain",
  HEART: "heart",
  HEARTBREAK: "heartbreak",
  TROPHY: "trophy",
  STAR: "star",
  FIRE: "fire",
  MONEY: "money",
  COIN: "coin",
  GOLDBAR: "goldbar",
  DIAMOND: "diamond",
  CROWN: "crown",
  GIFT: "gift",
  CLOCK: "clock",
  ALARMCLOCK: "alarmclock",
  STOPWATCH: "stopwatch",
  LOCK: "lock",
  BOOK: "book",
  LIGHTNING: "lightning",
  SPARKLES: "sparkles",
  WAND: "wand",
  GAUNTLET: "gauntlet",
  SKULL: "skull",
  DEMON: "demon",
  GOBLIN: "goblin",
  SOCK: "sock",
  MISMATCHSOCK: "mismatchsock",
  DIAMONDSOCK: "diamondsock",
  GOLDENSOCKS: "goldensocks",
  LAUNDRYPILE: "laundrypile",
  BASKET: "basket",
  HOUSE: "house",
  HOUSEFIRE: "housefire",
  TV: "tv",
  WASHINGMAC: "washingmac",
  CDPLAYER: "cdplayer",
  RADIO: "radio",
  VHS: "vhs",
  RECORD: "record",
  MUSICNOTE: "musicnote",
  BARBELL: "barbell",
  SHOES: "shoes",
  HAT: "hat",
  EGG: "egg",
  BUTTER: "butter",
  GLASS: "glass",
  HANDS: "hands",
  TEETH: "teeth",
  EYEBALL: "eyeball",
  BEETLE: "beetle",
  STAGBEETLE: "stagbeetle",
  MOUSE: "mouse",
  STROLLER: "stroller",
  WALL: "wall",
  BULLSEYE: "bullseye",
  REDX: "redx",
  MEDAL: "medal",
  SONIC: "sonic",
  SUNDIAL: "sundial",
  SNAPPY: "snappy",
  GOLDENSNAPPY: "goldensnappy",
  DIAMONDSNAPPY: "diamondsnappy",
  POKE: "pokeball",
  GOLDENORB: "goldenorb",
  DIAMONDTROPHY: "diamondtrophy",
  DIAMONDHEART: "diamondheart",
  ASTEROID: "asteroid",
};

// All available icons in the game
const GAME_ICONS = [
  {
    id: ICON.ASTEROID,
    file: "icon-asteroid.png",
    name: "Asteroid",
  },
  {
    id: ICON.DIAMONDHEART,
    file: "icon-diamondheart.png",
    name: "Diamond Heart",
  },
  {
    id: ICON.DIAMONDTROPHY,
    file: "icon-diamondtrophy.png",
    name: "Diamond Trophy",
  },
  { id: ICON.GOLDENORB, file: "icon-goldenorb.png", name: "Golden Orb" },
  {
    id: ICON.DIAMONDSNAPPY,
    file: "icon-diamondsnap.png",
    name: "Diamond Snap",
  },
  { id: ICON.GOLDENSNAPPY, file: "icon-goldsnap.png", name: "Golden Snap" },
  { id: ICON.WOLF, file: "icon-wolf.png", name: "Wolf" },
  { id: ICON.POKE, file: "icon-poke.png", name: "Pokeball" },
  { id: ICON.WIZARDHAT, file: "icon-wizard.png", name: "Wizard Hat" },
  { id: ICON.WIZARD, file: "icon-fullwizard.png", name: "Wizard" },
  { id: ICON.BRAIN, file: "icon-brain.png", name: "Brain" },
  { id: ICON.HEART, file: "icon-heart.png", name: "Heart" },
  { id: ICON.HEARTBREAK, file: "icon-heartbreak.png", name: "Heartbreak" },
  { id: ICON.TROPHY, file: "icon-trophy.png", name: "Trophy" },
  { id: ICON.STAR, file: "icon-star.png", name: "Star" },
  { id: ICON.FIRE, file: "icon-fire3.png", name: "Fire" },
  { id: ICON.MONEY, file: "icon-money.png", name: "Money" },
  { id: ICON.COIN, file: "icon-coin.png", name: "Coin" },
  { id: ICON.GOLDBAR, file: "icon-goldbar.png", name: "Gold Bar" },
  { id: ICON.DIAMOND, file: "icon-diamond.png", name: "Diamond" },
  { id: ICON.CROWN, file: "icon-crown.png", name: "Crown" },
  { id: ICON.GIFT, file: "icon-gift.png", name: "Gift" },
  { id: ICON.CLOCK, file: "icon-clock.png", name: "Clock" },
  { id: ICON.ALARMCLOCK, file: "icon-alarmclock.png", name: "Alarm Clock" },
  { id: ICON.STOPWATCH, file: "icon-stopwatch.png", name: "Stopwatch" },
  { id: ICON.LOCK, file: "icon-lock.png", name: "Lock" },
  { id: ICON.BOOK, file: "icon-book.png", name: "Book" },
  { id: ICON.LIGHTNING, file: "icon-lightning.png", name: "Lightning" },
  { id: ICON.SPARKLES, file: "icon-sparkles.png", name: "Sparkles" },
  { id: ICON.WAND, file: "icon-wand.png", name: "Wand" },
  { id: ICON.GAUNTLET, file: "icon-gauntlet.png", name: "Gauntlet" },
  { id: ICON.SKULL, file: "icon-skull.png", name: "Skull" },
  { id: ICON.DEMON, file: "icon-demon.png", name: "Demon" },
  { id: ICON.GOBLIN, file: "icon-goblin.png", name: "Goblin" },
  { id: ICON.SOCK, file: "icon-sock.png", name: "Sock" },
  { id: ICON.SNAPPY, file: "icon-snappy.png", name: "Snappy" },
  {
    id: ICON.MISMATCHSOCK,
    file: "icon-mismatchsock.png",
    name: "Mismatched Socks",
  },
  { id: ICON.DIAMONDSOCK, file: "icon-diamondsock.png", name: "Diamond Sock" },
  { id: ICON.GOLDENSOCKS, file: "icon-goldensocks.png", name: "Golden Socks" },
  { id: ICON.LAUNDRYPILE, file: "icon-laundrypile.png", name: "Laundry Pile" },
  { id: ICON.BASKET, file: "icon-basket.png", name: "Basket" },
  { id: ICON.HOUSE, file: "icon-house.png", name: "House" },
  { id: ICON.HOUSEFIRE, file: "icon-housefire.png", name: "House Fire" },
  { id: ICON.TV, file: "icon-tv.png", name: "TV" },
  { id: ICON.WASHINGMAC, file: "icon-washingmac.png", name: "Washing Machine" },
  { id: ICON.CDPLAYER, file: "icon-cdplayer.png", name: "CD Player" },
  { id: ICON.RADIO, file: "icon-radio.png", name: "Radio" },
  { id: ICON.VHS, file: "icon-vhs.png", name: "VHS" },
  { id: ICON.RECORD, file: "icon-record.png", name: "Record" },
  { id: ICON.MUSICNOTE, file: "icon-musicnote.png", name: "Music Note" },
  { id: ICON.BARBELL, file: "icon-barbell.png", name: "Barbell" },
  { id: ICON.SHOES, file: "icon-shoes.png", name: "Shoes" },
  { id: ICON.HAT, file: "icon-hat.png", name: "Hat" },
  { id: ICON.EGG, file: "icon-egg.png", name: "Egg" },
  { id: ICON.BUTTER, file: "icon-butter.png", name: "Butter" },
  { id: ICON.GLASS, file: "icon-glass.png", name: "Glass" },
  { id: ICON.HANDS, file: "icon-hands.png", name: "Praying Hands" },
  { id: ICON.TEETH, file: "icon-teeth.png", name: "Teeth" },
  { id: ICON.EYEBALL, file: "icon-eyeball.png", name: "Eyeball" },
  { id: ICON.BEETLE, file: "icon-beetle.png", name: "Beetle" },
  { id: ICON.STAGBEETLE, file: "icon-stagbeetle.png", name: "Stag Beetle" },
  { id: ICON.MOUSE, file: "icon-mouse.png", name: "Mouse" },
  { id: ICON.STROLLER, file: "icon-stroller.png", name: "Stroller" },
  { id: ICON.WALL, file: "icon-wall.png", name: "Wall" },
  { id: ICON.BULLSEYE, file: "icon-bullseye.png", name: "Bullseye" },
  { id: ICON.REDX, file: "icon-redx.png", name: "Red X" },
  { id: ICON.MEDAL, file: "icon-1stmedal.png", name: "1st Medal" },
  { id: ICON.SONIC, file: "icon-sonic.png", name: "Sonic" },
  { id: ICON.SUNDIAL, file: "icon-sundial.png", name: "Sun Dial" },
];

// Post messages with icon reactions
// Each post has:
// - text: The message displayed to the player
// - perfectIcons: Array of icon IDs that give +5 points (perfect answers)
// - correctIcons: Array of icon IDs that give +2 points (good answers)
// - neutralIcons: Array of icon IDs that give 0 points (okay answers)
// - wrongIcons: Array of icon IDs that give -3 points (bad answers)
// - horribleIcons: Array of icon IDs that give -6 points (terrible answers)

const GAME_MESSAGES = [
  {
    text: "The socks have achieved sentience. Negotiating terms of surrender.",
    perfectIcons: [ICON.LAUNDRYPILE],
    correctIcons: [ICON.DEMON],
    neutralIcons: [ICON.COIN, ICON.HANDS],
    wrongIcons: [ICON.HEART],
    horribleIcons: [ICON.POKE],
  },
  {
    text: "Tried to wake up this morning on time. Body said 'counterpoint: no.'",
    perfectIcons: [ICON.ALARMCLOCK],
    correctIcons: [ICON.BRAIN],
    neutralIcons: [ICON.HEARTBREAK, ICON.SHOES],
    wrongIcons: [ICON.TROPHY],
    horribleIcons: [ICON.STAR],
  },
  {
    text: "Kitchen experiment reached its final form. I'm not getting the damage depoist back.",
    perfectIcons: [ICON.HOUSEFIRE],
    correctIcons: [ICON.FIRE],
    neutralIcons: [ICON.SPARKLES, ICON.GLASS],
    wrongIcons: [ICON.TEETH],
    horribleIcons: [ICON.DIAMONDTROPHY],
  },
  {
    text: "Can't find my phone... oh wait I'm texting on it now.",
    perfectIcons: [ICON.EYEBALL],
    correctIcons: [ICON.BRAIN],
    neutralIcons: [ICON.STAGBEETLE, ICON.LIGHTNING],
    wrongIcons: [ICON.DEMON],
    horribleIcons: [ICON.MOUSE],
  },
  {
    text: "Parallel parked on the first try. Witnesses requested autographs, injured did as well.",
    perfectIcons: [ICON.TROPHY],
    correctIcons: [ICON.MEDAL],
    neutralIcons: [ICON.MONEY, ICON.DEMON],
    wrongIcons: [ICON.LAUNDRYPILE],
    horribleIcons: [ICON.MISMATCHSOCK],
  },
  {
    text: "Casting spells so I don't forget where I put my keys.",
    perfectIcons: [ICON.WIZARD],
    correctIcons: [ICON.SPARKLES],
    neutralIcons: [ICON.BRAIN, ICON.HOUSE],
    wrongIcons: [ICON.SONIC],
    horribleIcons: [ICON.COIN],
  },
  {
    text: "Sang my song and got voted out within 10 seconds.",
    perfectIcons: [ICON.REDX],
    correctIcons: [ICON.MUSICNOTE],
    neutralIcons: [ICON.SUNDIAL, ICON.DIAMONDHEART],
    wrongIcons: [ICON.MEDAL],
    horribleIcons: [ICON.BOOK],
  },
  {
    text: "I really gotta get to my laundry sometime this week. I'm losing the war.",
    perfectIcons: [ICON.MISMATCHSOCK],
    correctIcons: [ICON.LAUNDRYPILE],
    neutralIcons: [ICON.SNAPPY, ICON.DEMON],
    wrongIcons: [ICON.TROPHY],
    horribleIcons: [ICON.HEART],
  },
  {
    text: "Have a weird craving for fat in stick form. Only thing I wanna eat.",
    perfectIcons: [ICON.TEETH],
    correctIcons: [ICON.BUTTER],
    neutralIcons: [ICON.WASHINGMAC, ICON.WOLF],
    wrongIcons: [ICON.MONEY],
    horribleIcons: [ICON.EYEBALL],
  },
  {
    text: "Can't tell time with this damn sun being blocked.",
    perfectIcons: [ICON.SUNDIAL],
    correctIcons: [ICON.ASTEROID],
    neutralIcons: [ICON.STOPWATCH, ICON.TEETH],
    wrongIcons: [ICON.TV],
    horribleIcons: [ICON.GOBLIN],
  },
  {
    text: "Told a joke and nobody laughed. Eggsellent achievement.",
    perfectIcons: [ICON.EGG],
    correctIcons: [ICON.TROPHY],
    neutralIcons: [ICON.HOUSEFIRE, ICON.DIAMONDSNAPPY],
    wrongIcons: [ICON.WIZARDHAT],
    horribleIcons: [ICON.RADIO],
  },
  {
    text: "Successfully opened a jar, required 2 fingers and a hammer. I might be getting old.",
    perfectIcons: [ICON.SNAPPY],
    correctIcons: [ICON.WALL],
    neutralIcons: [ICON.DIAMONDHEART, ICON.SOCK],
    wrongIcons: [ICON.HANDS],
    horribleIcons: [ICON.STROLLER],
  },
  {
    text: "Finally understood that confusing plot twist. Three years later.",
    perfectIcons: [ICON.BRAIN],
    correctIcons: [ICON.CLOCK],
    neutralIcons: [ICON.HANDS, ICON.SPARKLES],
    wrongIcons: [ICON.GOLDENORB],
    horribleIcons: [ICON.MOUSE],
  },
  {
    text: "Coffee stayed hot all day - not suprised.",
    perfectIcons: [ICON.HOUSEFIRE],
    correctIcons: [ICON.DEMON],
    neutralIcons: [ICON.SPARKLES, ICON.STAR],
    wrongIcons: [ICON.LAUNDRYPILE],
    horribleIcons: [ICON.BEETLE],
  },
  {
    text: "Washed the dishes and clothes in one go. I am unstoppable.",
    perfectIcons: [ICON.WASHINGMAC],
    correctIcons: [ICON.BRAIN],
    neutralIcons: [ICON.VHS, ICON.POKE],
    wrongIcons: [ICON.ALARMCLOCK],
    horribleIcons: [ICON.BEETLE],
  },
  {
    text: "Got hit again, they said it couldn't happen twice...",
    perfectIcons: [ICON.LIGHTNING],
    correctIcons: [ICON.SKULL],
    neutralIcons: [ICON.DIAMOND, ICON.BARBELL],
    wrongIcons: [ICON.ALARMCLOCK],
    horribleIcons: [ICON.WOLF],
  },
  {
    text: "I forgot to water my plastic plants. Why do I feel bad when they're already dead?",
    perfectIcons: [ICON.SKULL],
    correctIcons: [ICON.GLASS],
    neutralIcons: [ICON.BUTTER, ICON.EGG],
    wrongIcons: [ICON.STAGBEETLE],
    horribleIcons: [ICON.STAR],
  },
  {
    text: "These monsters really are pocket sized!",
    perfectIcons: [ICON.POKE],
    correctIcons: [ICON.EGG],
    neutralIcons: [ICON.GOLDENSNAPPY, ICON.MISMATCHSOCK],
    wrongIcons: [ICON.GIFT],
    horribleIcons: [ICON.SPARKLES],
  },
  {
    text: "Returned the shopping cart to my house for future use with my baby.",
    perfectIcons: [ICON.STROLLER],
    correctIcons: [ICON.BULLSEYE],
    neutralIcons: [ICON.CDPLAYER, ICON.SKULL],
    wrongIcons: [ICON.POKE],
    horribleIcons: [ICON.GOLDBAR],
  },
  {
    text: "My internet didn't disconnect during the meeting so I just left early and faked it.",
    perfectIcons: [ICON.CLOCK],
    correctIcons: [ICON.MOUSE],
    neutralIcons: [ICON.LAUNDRYPILE, ICON.HAT],
    wrongIcons: [ICON.ASTEROID],
    horribleIcons: [ICON.TEETH],
  },
  {
    text: "Baked something that didn't burn. It was me.",
    perfectIcons: [ICON.TROPHY],
    correctIcons: [ICON.STAR],
    neutralIcons: [ICON.MEDAL, ICON.MISMATCHSOCK],
    wrongIcons: [ICON.WIZARDHAT],
    horribleIcons: [ICON.BARBELL],
  },
  {
    text: "Pulled out two random socks and they matched. Witchcraft confirmed.",
    perfectIcons: [ICON.MISMATCHSOCK],
    correctIcons: [ICON.WIZARDHAT],
    neutralIcons: [ICON.HEARTBREAK, ICON.BASKET],
    wrongIcons: [ICON.SPARKLES],
    horribleIcons: [ICON.FIRE],
  },
  {
    text: "Finished reading a book before buying three more. Addiction has been beaten.",
    perfectIcons: [ICON.BOOK],
    correctIcons: [ICON.DIAMOND],
    neutralIcons: [ICON.BULLSEYE, ICON.LOCK],
    wrongIcons: [ICON.GAUNTLET],
    horribleIcons: [ICON.RECORD],
  },
  {
    text: "Coffee prices through the roof, going to be broke before long.",
    perfectIcons: [ICON.DIAMOND],
    correctIcons: [ICON.COIN],
    neutralIcons: [ICON.MOUSE, ICON.DIAMONDTROPHY],
    wrongIcons: [ICON.EGG],
    horribleIcons: [ICON.SOCK],
  },
  {
    text: "Answered an email immediately, now they've sent 15 more. I suck!",
    perfectIcons: [ICON.GOLDENSNAPPY],
    correctIcons: [ICON.SONIC],
    neutralIcons: [ICON.EYEBALL, ICON.STROLLER],
    wrongIcons: [ICON.BULLSEYE],
    horribleIcons: [ICON.MUSICNOTE],
  },
  {
    text: "Made a to-do list and just watched home movies instead. Who am I?",
    perfectIcons: [ICON.VHS],
    correctIcons: [ICON.TV],
    neutralIcons: [ICON.HANDS, ICON.GAUNTLET],
    wrongIcons: [ICON.BASKET],
    horribleIcons: [ICON.MISMATCHSOCK],
  },
  {
    text: "Finally cleaned my lucky socks. Everything is now possible.",
    perfectIcons: [ICON.DIAMONDSOCK],
    correctIcons: [ICON.WASHINGMAC],
    neutralIcons: [ICON.STOPWATCH, ICON.GOLDENORB],
    wrongIcons: [ICON.HAT],
    horribleIcons: [ICON.WIZARDHAT],
  },
  {
    text: "The universe delivered exactly what I ordered. Insurance policy paid payout is huge!",
    perfectIcons: [ICON.FIRE],
    correctIcons: [ICON.HOUSEFIRE],
    neutralIcons: [ICON.DIAMOND, ICON.RADIO],
    wrongIcons: [ICON.WIZARD],
    horribleIcons: [ICON.SKULL],
  },
  {
    text: "Remembered my password on the first try. I'm a genius.",
    perfectIcons: [ICON.BRAIN],
    correctIcons: [ICON.LIGHTNING],
    neutralIcons: [ICON.LOCK, ICON.FIRE],
    wrongIcons: [ICON.RECORD],
    horribleIcons: [ICON.WAND],
  },
  {
    text: "Folded a fitted sheet correctly. I've peaked, might as well call it here.",
    perfectIcons: [ICON.TROPHY],
    correctIcons: [ICON.MEDAL],
    neutralIcons: [ICON.BASKET, ICON.WASHINGMAC],
    wrongIcons: [ICON.MOUSE],
    horribleIcons: [ICON.HEART],
  },
  {
    text: "Channeled my inner beast and howled at the moon. Neighbors loved it.",
    perfectIcons: [ICON.WOLF],
    correctIcons: [ICON.DEMON],
    neutralIcons: [ICON.GOBLIN, ICON.ALARMCLOCK],
    wrongIcons: [ICON.GOLDENSNAPPY],
    horribleIcons: [ICON.BARBELL],
  },
  {
    text: "Couldn't solve the mystery novel, I'm guessing the butler did it anyway.",
    perfectIcons: [ICON.BOOK],
    correctIcons: [ICON.DIAMONDSNAPPY],
    neutralIcons: [ICON.EYEBALL, ICON.STOPWATCH],
    wrongIcons: [ICON.WIZARD],
    horribleIcons: [ICON.STROLLER],
  },
  {
    text: "My bank account whispered sweet nothings. They were right, no money to be found.",
    perfectIcons: [ICON.MONEY],
    correctIcons: [ICON.HEARTBREAK],
    neutralIcons: [ICON.FIRE, ICON.WALL],
    wrongIcons: [ICON.DIAMONDSOCK],
    horribleIcons: [ICON.DIAMONDTROPHY],
  },
  {
    text: "Found a diamond. It was my determination after all.",
    perfectIcons: [ICON.DIAMOND],
    correctIcons: [ICON.BARBELL],
    neutralIcons: [ICON.GAUNTLET, ICON.BULLSEYE],
    wrongIcons: [ICON.GOLDENSOCKS],
    horribleIcons: [ICON.LOCK],
  },
  {
    text: "A few snaps and they call you king in no time.",
    perfectIcons: [ICON.CROWN],
    correctIcons: [ICON.GAUNTLET],
    neutralIcons: [ICON.TROPHY, ICON.HOUSE],
    wrongIcons: [ICON.STAR],
    horribleIcons: [ICON.MISMATCHSOCK],
  },
  {
    text: "Asked my crush out with a gift, they didn't know who I was.",
    perfectIcons: [ICON.GIFT],
    correctIcons: [ICON.HEARTBREAK],
    neutralIcons: [ICON.HEART, ICON.WIZARDHAT],
    wrongIcons: [ICON.WAND],
    horribleIcons: [ICON.BRAIN],
  },
  {
    text: "Saw a tree split in two during a storm, it was rad.",
    perfectIcons: [ICON.LIGHTNING],
    correctIcons: [ICON.FIRE],
    neutralIcons: [ICON.SONIC, ICON.TV],
    wrongIcons: [ICON.WALL],
    horribleIcons: [ICON.STAGBEETLE],
  },
  {
    text: "My magic stick broke. I'm just a regular person now.",
    perfectIcons: [ICON.WAND],
    correctIcons: [ICON.HEARTBREAK],
    neutralIcons: [ICON.DIAMONDTROPHY, ICON.BRAIN],
    wrongIcons: [ICON.BARBELL],
    horribleIcons: [ICON.ASTEROID],
  },
  {
    text: "Found my keys on my keychain. Felt like a king!",
    perfectIcons: [ICON.LOCK],
    correctIcons: [ICON.CROWN],
    neutralIcons: [ICON.EYEBALL, ICON.VHS],
    wrongIcons: [ICON.DIAMONDSNAPPY],
    horribleIcons: [ICON.GOLDENORB],
  },
  {
    text: "My teeth fell out. Just kidding, I pulled them out.",
    perfectIcons: [ICON.TEETH],
    correctIcons: [ICON.REDX],
    neutralIcons: [ICON.STROLLER, ICON.EGG],
    wrongIcons: [ICON.FIRE],
    horribleIcons: [ICON.SKULL],
  },
  {
    text: "Became one with the watcher. Now I see all.",
    perfectIcons: [ICON.EYEBALL],
    correctIcons: [ICON.BRAIN],
    neutralIcons: [ICON.SHOES, ICON.BOOK],
    wrongIcons: [ICON.HOUSEFIRE],
    horribleIcons: [ICON.GAUNTLET],
  },
  {
    text: "A bug invaded my space. We negotiated peace.",
    perfectIcons: [ICON.BEETLE],
    correctIcons: [ICON.DIAMONDHEART],
    neutralIcons: [ICON.SUNDIAL, ICON.GOBLIN],
    wrongIcons: [ICON.LIGHTNING],
    horribleIcons: [ICON.SNAPPY],
  },
  {
    text: "The mouse in my house is roommate-adjacent now. He even pays rent in peanuts.",
    perfectIcons: [ICON.MOUSE],
    correctIcons: [ICON.HOUSE],
    neutralIcons: [ICON.BEETLE, ICON.SHOES],
    wrongIcons: [ICON.STOPWATCH],
    horribleIcons: [ICON.SOCK],
  },
  {
    text: "All house chores are done. That's an achievement.",
    perfectIcons: [ICON.HOUSE],
    correctIcons: [ICON.BASKET],
    neutralIcons: [ICON.MONEY, ICON.GIFT],
    wrongIcons: [ICON.SNAPPY],
    horribleIcons: [ICON.MONEY],
  },
  {
    text: "Hit the bullseye on my first attempt. And the second, and the third....",
    perfectIcons: [ICON.BULLSEYE],
    correctIcons: [ICON.TROPHY],
    neutralIcons: [ICON.STAR, ICON.LAUNDRYPILE],
    wrongIcons: [ICON.MISMATCHSOCK],
    horribleIcons: [ICON.BASKET],
  },
  {
    text: "Lifted 250lb today just like the workout tape. My muscles now have muscles.",
    perfectIcons: [ICON.BARBELL],
    correctIcons: [ICON.VHS],
    neutralIcons: [ICON.GAUNTLET, ICON.SKULL],
    wrongIcons: [ICON.STOPWATCH],
    horribleIcons: [ICON.RADIO],
  },
  {
    text: "Put on my shoes. I'm basically ready for anything.",
    perfectIcons: [ICON.SHOES],
    correctIcons: [ICON.MISMATCHSOCK],
    neutralIcons: [ICON.GOLDENSNAPPY, ICON.POKE],
    wrongIcons: [ICON.DIAMOND],
    horribleIcons: [ICON.VHS],
  },
  {
    text: "Found the hat but it's not like the wizard one in the books.",
    perfectIcons: [ICON.HAT],
    correctIcons: [ICON.BOOK],
    neutralIcons: [ICON.WIZARDHAT, ICON.WAND],
    wrongIcons: [ICON.BOOK],
    horribleIcons: [ICON.GIFT],
  },
  {
    text: "Cracked an egg and ate the shell, now I'm bleeding everywhere. Evolution.",
    perfectIcons: [ICON.EGG],
    correctIcons: [ICON.HANDS],
    neutralIcons: [ICON.STAGBEETLE, ICON.WALL],
    wrongIcons: [ICON.CROWN],
    horribleIcons: [ICON.SONIC],
  },
  {
    text: "Spread butter with my palm like an artist. The toast is confused.",
    perfectIcons: [ICON.BUTTER],
    correctIcons: [ICON.HANDS],
    neutralIcons: [ICON.EGG, ICON.GOLDENSOCKS],
    wrongIcons: [ICON.CROWN],
    horribleIcons: [ICON.DEMON],
  },
  {
    text: "My glass is half empty. Soon is will be completely empty. I'm so thirsty.",
    perfectIcons: [ICON.GLASS],
    correctIcons: [ICON.SUNDIAL],
    neutralIcons: [ICON.RECORD, ICON.TV],
    wrongIcons: [ICON.COIN],
    horribleIcons: [ICON.ASTEROID],
  },
  {
    text: "The needle didn't skip once. My music taste remains unquestioned.",
    perfectIcons: [ICON.RECORD],
    correctIcons: [ICON.GOLDENSNAPPY],
    neutralIcons: [ICON.BUTTER, ICON.TEETH],
    wrongIcons: [ICON.HAT],
    horribleIcons: [ICON.DIAMONDHEART],
  },
  {
    text: "Played a music note and nobody yelled at me. Progress has been made.",
    perfectIcons: [ICON.MUSICNOTE],
    correctIcons: [ICON.RADIO],
    neutralIcons: [ICON.ALARMCLOCK, ICON.GOLDBAR],
    wrongIcons: [ICON.SKULL],
    horribleIcons: [ICON.SUNDIAL],
  },
  {
    text: "My time management hack has gotten be several awards.",
    perfectIcons: [ICON.STOPWATCH],
    correctIcons: [ICON.MEDAL],
    neutralIcons: [ICON.WAND, ICON.BEETLE],
    wrongIcons: [ICON.HEARTBREAK],
    horribleIcons: [ICON.GOLDENSOCKS],
  },
  {
    text: "Can't fingure out how to unstick myself from this finger trap.",
    perfectIcons: [ICON.HANDS],
    correctIcons: [ICON.BRAIN],
    neutralIcons: [ICON.GOLDENSOCKS, ICON.STAGBEETLE],
    wrongIcons: [ICON.CROWN],
    horribleIcons: [ICON.GLASS],
  },
  {
    text: "Gonna blast through emerald hills in no time!",
    perfectIcons: [ICON.SONIC],
    correctIcons: [ICON.SHOES],
    neutralIcons: [ICON.LOCK, ICON.HAT],
    wrongIcons: [ICON.HOUSE],
    horribleIcons: [ICON.WALL],
  },
  {
    text: "Snapped so hard that the whole office looked at me. Perfection unlocked.",
    perfectIcons: [ICON.GOLDENSNAPPY],
    correctIcons: [ICON.TROPHY],
    neutralIcons: [ICON.GLASS, ICON.GOLDENORB],
    wrongIcons: [ICON.REDX],
    horribleIcons: [ICON.CDPLAYER],
  },
  {
    text: "The diamond finger tips caught the light. I'm sparkling.",
    perfectIcons: [ICON.DIAMONDSNAPPY],
    correctIcons: [ICON.SPARKLES],
    neutralIcons: [ICON.SNAPPY, ICON.WIZARDHAT],
    wrongIcons: [ICON.BASKET],
    horribleIcons: [ICON.WAND],
  },
  {
    text: "Caught a monster with one hand behind my back.",
    perfectIcons: [ICON.POKE],
    correctIcons: [ICON.TROPHY],
    neutralIcons: [ICON.LIGHTNING, ICON.WOLF],
    wrongIcons: [ICON.HEARTBREAK],
    horribleIcons: [ICON.TV],
  },
  {
    text: "Put some sparkly orbs up my rear, instantly felt the magic inside.",
    perfectIcons: [ICON.GOLDENORB],
    correctIcons: [ICON.WIZARD],
    neutralIcons: [ICON.EYEBALL, ICON.BOOK],
    wrongIcons: [ICON.GAUNTLET],
    horribleIcons: [ICON.MEDAL],
  },
  {
    text: "Won epic award at work for my stinky sock collection. The reward is that I was fired",
    perfectIcons: [ICON.SOCK],
    correctIcons: [ICON.DIAMONDTROPHY],
    neutralIcons: [ICON.WOLF, ICON.CDPLAYER],
    wrongIcons: [ICON.SONIC],
    horribleIcons: [ICON.HANDS],
  },
  {
    text: "Too green to loved, rich to be hated. Being Martha is hard work.",
    perfectIcons: [ICON.GOBLIN],
    correctIcons: [ICON.HEART],
    neutralIcons: [ICON.RADIO, ICON.CROWN],
    wrongIcons: [ICON.FIRE],
    horribleIcons: [ICON.RADIO],
  },
  {
    text: "A rock just went by as I was jamming to tunes. Close call.",
    perfectIcons: [ICON.ASTEROID],
    correctIcons: [ICON.CDPLAYER],
    neutralIcons: [ICON.HOUSEFIRE, ICON.SKULL],
    wrongIcons: [ICON.GOBLIN],
    horribleIcons: [ICON.SNAPPY],
  },
  {
    text: "Broke out the racecar rewinder today. Nostalgia activated.",
    perfectIcons: [ICON.VHS],
    correctIcons: [ICON.TV],
    neutralIcons: [ICON.RADIO, ICON.MOUSE],
    wrongIcons: [ICON.WASHINGMAC],
    horribleIcons: [ICON.WIZARDHAT],
  },
  {
    text: "Doing laundry and tuned into the best 2 hours of monster punk ever! Fate exists.",
    perfectIcons: [ICON.RADIO],
    correctIcons: [ICON.DIAMONDSOCK],
    neutralIcons: [ICON.GOLDBAR, ICON.BULLSEYE],
    wrongIcons: [ICON.SONIC],
    horribleIcons: [ICON.ASTEROID],
  },
  {
    text: "Using toothpaste to try and fix the scratches, but I don't think it's helping.",
    perfectIcons: [ICON.CDPLAYER],
    correctIcons: [ICON.RECORD],
    neutralIcons: [ICON.EYEBALL, ICON.HOUSEFIRE],
    wrongIcons: [ICON.RADIO],
    horribleIcons: [ICON.SOCK],
  },
  {
    text: "My TV actually turned on when I pressed the button. No juggling the batteries today!",
    perfectIcons: [ICON.TV],
    correctIcons: [ICON.SNAPPY],
    neutralIcons: [ICON.GIFT, ICON.HEART],
    wrongIcons: [ICON.MUSICNOTE],
    horribleIcons: [ICON.LAUNDRYPILE],
  },
  {
    text: "I put 4 pairs in and got 6 pairs out, I'm not complaining!",
    perfectIcons: [ICON.WASHINGMAC],
    correctIcons: [ICON.HEART],
    neutralIcons: [ICON.BASKET, ICON.GOBLIN],
    wrongIcons: [ICON.STROLLER],
    horribleIcons: [ICON.WIZARD],
  },
  {
    text: "Discovered a new wall in my house. Where did that come from?",
    perfectIcons: [ICON.WALL],
    correctIcons: [ICON.WAND],
    neutralIcons: [ICON.CROWN, ICON.DIAMONDSOCK],
    wrongIcons: [ICON.BRAIN],
    horribleIcons: [ICON.ASTEROID],
  },
  {
    text: "Starting to turn green with envy... oh wait, I've always been green.",
    perfectIcons: [ICON.GOBLIN],
    correctIcons: [ICON.BRAIN],
    neutralIcons: [ICON.DEMON, ICON.WIZARD],
    wrongIcons: [ICON.WAND],
    horribleIcons: [ICON.TROPHY],
  },
  {
    text: "Wore my cool drip to the store, everyone laughed.",
    perfectIcons: [ICON.WIZARDHAT],
    correctIcons: [ICON.GOLDENSOCKS],
    neutralIcons: [ICON.RADIO, ICON.MUSICNOTE],
    wrongIcons: [ICON.COIN],
    horribleIcons: [ICON.LAUNDRYPILE],
  },
  {
    text: "Gazed into the insects eyes. Ancient wisdom transferred.",
    perfectIcons: [ICON.STAGBEETLE],
    correctIcons: [ICON.GIFT],
    neutralIcons: [ICON.GOLDENSNAPPY, ICON.DIAMONDSNAPPY],
    wrongIcons: [ICON.SUNDIAL],
    horribleIcons: [ICON.DIAMONDSOCK],
  },
  {
    text: "Put things into my laundry and then was bit by a monster....again",
    perfectIcons: [ICON.BASKET],
    correctIcons: [ICON.WOLF],
    neutralIcons: [ICON.WALL, ICON.CLOCK],
    wrongIcons: [ICON.LAUNDRYPILE],
    horribleIcons: [ICON.CROWN],
  },
  {
    text: "Robbed a bank. Retirement is now feasible.",
    perfectIcons: [ICON.GOLDBAR],
    correctIcons: [ICON.MONEY],
    neutralIcons: [ICON.ASTEROID, ICON.LAUNDRYPILE],
    wrongIcons: [ICON.LOCK],
    horribleIcons: [ICON.LIGHTNING],
  },
  {
    text: "Flipped a coin three times in a row - EDGE EDGE EDGE. Destiny confirmed.",
    perfectIcons: [ICON.COIN],
    correctIcons: [ICON.STAR],
    neutralIcons: [ICON.TV, ICON.SUNDIAL],
    wrongIcons: [ICON.REDX],
    horribleIcons: [ICON.LAUNDRYPILE],
  },
  {
    text: "Contemplated my bone collection in the backyard. Needs more femurs.",
    perfectIcons: [ICON.SKULL],
    correctIcons: [ICON.EYEBALL],
    neutralIcons: [ICON.MUSICNOTE, ICON.BOOK],
    wrongIcons: [ICON.HEART],
    horribleIcons: [ICON.BARBELL],
  },
  {
    text: "Shadows that can tell the time? Magic confirmed.",
    perfectIcons: [ICON.SUNDIAL],
    correctIcons: [ICON.CLOCK],
    neutralIcons: [ICON.RECORD, ICON.BRAIN],
    wrongIcons: [ICON.DEMON],
    horribleIcons: [ICON.VHS],
  },
  {
    text: "Snapped my fingers and something actually happened.",
    perfectIcons: [ICON.SNAPPY],
    correctIcons: [ICON.SPARKLES],
    neutralIcons: [ICON.CDPLAYER, ICON.LIGHTNING],
    wrongIcons: [ICON.BEETLE],
    horribleIcons: [ICON.HEARTBREAK],
  },
  {
    text: "Drove through a rainbow and now my car is so clean, the leprechaun's still stuck in my wheel well though.",
    perfectIcons: [ICON.SPARKLES],
    correctIcons: [ICON.STAR],
    neutralIcons: [ICON.HEART, ICON.MEDAL],
    wrongIcons: [ICON.BEETLE],
    horribleIcons: [ICON.REDX],
  },
  {
    text: "Ended up winning on a gameshow, I went last and everyone else had already failed!",
    perfectIcons: [ICON.STAR],
    correctIcons: [ICON.TROPHY],
    neutralIcons: [ICON.ASTEROID, ICON.CDPLAYER],
    wrongIcons: [ICON.MOUSE],
    horribleIcons: [ICON.HOUSE],
  },
  {
    text: "Found all the stones, now I'm the real winner!",
    perfectIcons: [ICON.GAUNTLET],
    correctIcons: [ICON.TROPHY],
    neutralIcons: [ICON.BARBELL, ICON.COIN],
    wrongIcons: [ICON.STAGBEETLE],
    horribleIcons: [ICON.STOPWATCH],
  },
  {
    text: "Channeled pure demon energy. People laughted so I smote them down.",
    perfectIcons: [ICON.DEMON],
    correctIcons: [ICON.LIGHTNING],
    neutralIcons: [ICON.FIRE, ICON.TV],
    wrongIcons: [ICON.STROLLER],
    horribleIcons: [ICON.MUSICNOTE],
  },
  {
    text: "The elastic bands are never gonna break on these bad boi's!",
    perfectIcons: [ICON.GOLDENSOCKS],
    correctIcons: [ICON.SNAPPY],
    neutralIcons: [ICON.GOLDBAR, ICON.GIFT],
    wrongIcons: [ICON.RADIO],
    horribleIcons: [ICON.EGG],
  },
  {
    text: "Bought gold, then the price crashed. Just my luck.",
    perfectIcons: [ICON.HEARTBREAK],
    correctIcons: [ICON.GOLDBAR],
    neutralIcons: [ICON.ALARMCLOCK, ICON.SKULL],
    wrongIcons: [ICON.VHS],
    horribleIcons: [ICON.WASHINGMAC],
  },
  {
    text: "Couldn't find a full costume, so I made due with what I had.",
    perfectIcons: [ICON.GAUNTLET],
    correctIcons: [ICON.HAT],
    neutralIcons: [ICON.BARBELL, ICON.COIN],
    wrongIcons: [ICON.CDPLAYER],
    horribleIcons: [ICON.BUTTER],
  },
  {
    text: "Ran so fast that they gave me an award! I just was trying to get away from chores.",
    perfectIcons: [ICON.MEDAL],
    correctIcons: [ICON.TROPHY],
    neutralIcons: [ICON.CROWN, ICON.SNAPPY],
    wrongIcons: [ICON.GLASS],
    horribleIcons: [ICON.WALL],
  },
  {
    text: "Mach 1 achieved on the toilet. The world can't keep up.",
    perfectIcons: [ICON.SONIC],
    correctIcons: [ICON.GOLDENORB],
    neutralIcons: [ICON.ASTEROID, ICON.CLOCK],
    wrongIcons: [ICON.TV],
    horribleIcons: [ICON.HAT],
  },
  {
    text: "Funniest home videos? So anything with my brothers face then.",
    perfectIcons: [ICON.VHS],
    correctIcons: [ICON.GOBLIN],
    neutralIcons: [ICON.WIZARD, ICON.WAND],
    wrongIcons: [ICON.HOUSE],
    horribleIcons: [ICON.MEDAL],
  },
  {
    text: "I collect weird things and then I post about them... why am I like this? ",
    perfectIcons: [ICON.STAGBEETLE],
    correctIcons: [ICON.BEETLE],
    neutralIcons: [ICON.MOUSE, ICON.BUTTER],
    wrongIcons: [ICON.SOCK],
    horribleIcons: [ICON.SHOES],
  },
  {
    text: "My tough heart can't be broken anymore, and just in time too!",
    perfectIcons: [ICON.DIAMONDHEART],
    correctIcons: [ICON.ALARMCLOCK],
    neutralIcons: [ICON.BEETLE, ICON.CROWN],
    wrongIcons: [ICON.BUTTER],
    horribleIcons: [ICON.GOLDENSNAPPY],
  },
  {
    text: "Gazed into infinity and now my head hurts and my teeth are falling out.",
    perfectIcons: [ICON.EYEBALL],
    correctIcons: [ICON.TEETH],
    neutralIcons: [ICON.SNAPPY, ICON.SOCK],
    wrongIcons: [ICON.MUSICNOTE],
    horribleIcons: [ICON.BULLSEYE],
  },
  {
    text: "Ruined my friends backswing with the perfect noise. Then locked in my score",
    perfectIcons: [ICON.SNAPPY],
    correctIcons: [ICON.LOCK],
    neutralIcons: [ICON.HANDS, ICON.WIZARDHAT],
    wrongIcons: [ICON.WASHINGMAC],
    horribleIcons: [ICON.BOOK],
  },
  {
    text: "I keep throwing my balls at the bugs but nothing happens.",
    perfectIcons: [ICON.POKE],
    correctIcons: [ICON.STAGBEETLE],
    neutralIcons: [ICON.STAR, ICON.LIGHTNING],
    wrongIcons: [ICON.WOLF],
    horribleIcons: [ICON.DIAMONDSNAPPY],
  },
  {
    text: "Huffed 10 tonnes of paint and never felt this good.",
    perfectIcons: [ICON.DIAMONDTROPHY],
    correctIcons: [ICON.SKULL],
    neutralIcons: [ICON.SHOES, ICON.MEDAL],
    wrongIcons: [ICON.CLOCK],
    horribleIcons: [ICON.DIAMONDSNAPPY],
  },
  {
    text: "Who knew eating 10 extra greasy hamburgers would give me a heartattack?",
    perfectIcons: [ICON.HEART],
    correctIcons: [ICON.STOPWATCH],
    neutralIcons: [ICON.GOLDENSOCKS, ICON.ASTEROID],
    wrongIcons: [ICON.SHOES],
    horribleIcons: [ICON.HOUSEFIRE],
  },
  {
    text: "Moons out, hairs on, running down to a big block party!",
    perfectIcons: [ICON.WOLF],
    correctIcons: [ICON.SONIC],
    neutralIcons: [ICON.DEMON, ICON.REDX],
    wrongIcons: [ICON.DIAMONDHEART],
    horribleIcons: [ICON.CLOCK],
  },
  {
    text: "I'm now king but I'm not allowed to wear my comft clothes anymore.",
    perfectIcons: [ICON.CROWN],
    correctIcons: [ICON.SOCK],
    neutralIcons: [ICON.TEETH, ICON.DIAMONDSOCK],
    wrongIcons: [ICON.EYEBALL],
    horribleIcons: [ICON.ALARMCLOCK],
  },
  {
    text: "Can't burn all 20, so I'm unable to get the entire album - bummer.",
    perfectIcons: [ICON.CDPLAYER],
    correctIcons: [ICON.RECORD],
    neutralIcons: [ICON.HAT, ICON.STROLLER],
    wrongIcons: [ICON.DIAMONDTROPHY],
    horribleIcons: [ICON.ALARMCLOCK],
  },
  {
    text: "Why is that person's pet just a collection of bird eggs?",
    perfectIcons: [ICON.EGG],
    correctIcons: [ICON.POKE],
    neutralIcons: [ICON.VHS, ICON.REDX],
    wrongIcons: [ICON.GOLDBAR],
    horribleIcons: [ICON.DIAMOND],
  },
];

// Game scoring settings
const GAME_SCORING = {
  perfectPoints: 5, // Points for perfect icon
  correctPoints: 2, // Points for correct icon
  neutralPoints: 0, // Points for neutral icon
  wrongPoints: -3, // Points for wrong icon
  horriblePoints: -6, // Points for horrible icon
  timeoutPenalty: -2, // Points lost when time runs out
  fastBonus: 2, // Bonus for <1s reaction
  quickBonus: 1, // Bonus for <2s reaction
  targetScore: 500, // Score needed to win
  targetScoreLose: -100, // Score needed to lose
  streak5Multiplier: 2, // Multiplier at 5 streak
  streak10Multiplier: 3, // Multiplier at 10 streak
  postTimeLimit: 12000, // Time limit per post in milliseconds (10 seconds)
};
